name: Executar Testes Playwright

on:
  push:
    branches: [ main ] # Roda quando há um push na branch 'main'
  pull_request:
    branches: [ main ] # Roda quando um pull request é aberto para a 'main'

jobs:
  test:
    runs-on: ubuntu-latest # Usa uma máquina virtual Linux
    steps:
    # Passo 1: Clona o seu repositório para dentro da máquina virtual
    - name: Check out repository code
      uses: actions/checkout@v4

    # Passo 2: Configura o ambiente Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Passo 3: Instala as dependências do projeto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps # O --with-deps é importante para o Linux

    # Passo 4: Roda os testes em modo headless (sem interface gráfica)
    - name: Run Pytest tests
      run: python -m pytest --headless --html=report.html

    # Passo 5: Salva o relatório de testes como um "artefato"
    - name: Upload test report
      # Roda sempre, mesmo se os testes falharem, para que possamos ver o relatório do erro
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: report.html
        retention-days: 7 # Guarda o relatório por 7 dias